language: node_js
node_js:
  - 'stable'
before_install:
  - export NODE_ENV=testing
sudo: required
services:
  - mongodb
script: 
  - npm run lint
  - npm run test
  - npm run coverage
notifications:
  slack: bwekfastclub:apMLylCPCrM8rZTKlRkUOohL
